modifyLineBreaks:
  preserveBlankLines: 1
  condenseMultipleBlankLinesInto: 1  
  textWrapOptions:
    columns: 80
  environments:
    BeginStartsOnOwnLine: 1
    EndStartsOnOwnLine: 1
    BlockStartsOnOwnLine: 1
    blocksEndBefore:
      commentOnOwnLine: 1
      verbatim: 1    
      filecontents: 1
      other: \\section\*\{